# Generated by Django 2.1.5 on 2019-02-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20190205_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='like_user_set',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
