# Generated by Django 2.1.5 on 2019-02-09 02:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='available_dates_end',
            field=models.DateField(default=datetime.date(2019, 3, 11), null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
