# Generated by Django 2.1.5 on 2019-02-09 03:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20190209_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='available_dates_start',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
