# Generated by Django 2.1.5 on 2019-02-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20190209_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='address',
        ),
    ]
