# Generated by Django 2.1.5 on 2019-02-09 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20190209_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Home')),
            ],
        ),
    ]
